trigger: none
pr: none

variables: 
- name: 'devopsAccount' # new variable defined in YAML
  value: 'thecodemanual'
- name: 'projectName' # new variable defined in YAML
  value: 'DevOps Manual'

steps:
- bash: ls $(Build.SourcesDirectory)
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        # Encode the Personal Access Token (PAT)
        $AzureDevOpsAuthenicationHeader = @{Authorization = 'Basic ' + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$(System.AccessToken)")) }

        # Get a list of releases
        $uri = "https://dev.azure.com/$(devopsAccount)/$(projectName)/_apis/build/builds/$(Build.BuildId)/logs/6?api-version=5.1"

        Write-Host $uri

        # Invoke the REST call
        $result = Invoke-RestMethod -Uri $uri -Method Get -Headers $AzureDevOpsAuthenicationHeader

        Write-Host $result
        Write-Host "##vso[task.setvariable variable=high]$result"

# - pwsh: Start-Sleep -Seconds 60