parameters:
- name: environment
  displayName: Environment
  type: string
  default: QA
  values:
  - QA
  - PROD

trigger: none
pr: none

stages:
- stage:
  displayName: 'Build and Restore'
  variables:
  - group: ${{ parameters.environment }}
  jobs:
    - job:
      steps:
      - script: echo $(isProd)
      - script: echo $(name) # uses macro syntax | run time expression doesn't work for templates $[variables.name] 
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'env | sort'
