# https://stackoverflow.com/questions/64043553/how-to-start-previous-successful-release-automatically-in-devops-vsts/64044773?noredirect=1#comment113255370_64044773

trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

steps:
- task: TriggerPipeline@1
  inputs:
    serviceConnection: 'DevOps TheCodeManual'
    project: '4fa6b279-3db9-4cb0-aab8-e06c2ad550b2'
    Pipeline: 'Release'
    releaseDefinition: 'ReleaseWithVariableUpdate'