# https://stackoverflow.com/questions/65219176/conditional-stage-execution-in-azure-devops-pipelines

name: multistage

trigger: none
pr: none

stages:
  - stage: plan_dev
    jobs:
    - job: terraform_plan_dev
      steps:
      - bash: echo '##vso[task.setvariable variable=terraform_plan_exitcode;isOutput=true]2'
        name: terraform_plan

  - stage: apply_dev
    dependsOn: plan_dev
    variables:
      varFromA: $[ stageDependencies.plan_dev.terraform_plan_dev.outputs['terraform_plan.terraform_plan_exitcode'] ]
    condition: eq(dependencies.plan_dev.outputs['terraform_plan_dev.terraform_plan.terraform_plan_exitcode'], 2)
    jobs:
    - job: apply_dev
      steps:
      - bash: echo 'apply $(varFromA)'
        name: terraform_apply
