# https://stackoverflow.com/questions/64978458/validate-gitcommit-message-when-pr/64980023#64980023

trigger: none
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo '$(Build.SourceVersionMessage)'
    echo '$(Build.SourceVersion)'
  displayName: 'Source version details'
- pwsh: |
    git log -1 --pretty=oneline --abbrev-commit
  continueOnError: true
- pwsh: |
    git show $(Build.SourceVersion) --no-patch
- pwsh: |
    git log --format=%B -n 1 $(Build.SourceVersion)
