# https://stackoverflow.com/questions/67603812/how-can-i-prompt-for-variables-when-launching-azure-devops-pipelines

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: versionName
  value: ''

steps:
- script: |
    echo $(versionName)
    echo $(SomeVar)
    echo $(FromRun)
  displayName: 'Run a one-line script'

