# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
- group: Some-secrets
- name: var2
  value: true
- name: var1
  value: $[or(eq(variables['var2'], true), ne(variables['Mode'], 'dev'))]


pool:
  vmImage: ubuntu-latest

steps:
- script: env | sort
  displayName: 'Display env variables'

- script: |
    echo "$(var1)"
    echo "$(var2)"

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
- script: |
    python -m pip install --upgrade pip
    printenv
- task: Pythonscript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './script.py'
  env:
    usernameot: $(usernameot)
    passwordot: $(passwordot)