#https://stackoverflow.com/questions/69175794/yaml-pipeline-doesnt-compile-parameter-unexpected-value-in-azure-devops-serv/69177164#69177164
trigger: none

#VARIABLES
variables:
  BuildPlatform: 'x64'
  BuildConfiguration: 'release'

#PARAMETERS
parameters:
- name: 'MATLAB_upgrade'
  displayName: 'Upgrade Matlab binaries'
  type: boolean
  default: false

#STEPS
steps:
- pwsh: |
    echo "$(BuildPlatform)"
    echo "${{ parameters.MATLAB_upgrade}}"
