# https://stackoverflow.com/questions/64173113/how-to-run-an-aws-cli-elastic-beanstalk-wait-command-in-azure-devops

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- pwsh: aws --version
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'