# https://stackoverflow.com/questions/64711236/running-a-yaml-build-pipeline-manually-with-artifacts-selected-from-resources-in
trigger: none
pr: none

name: pipelineB

resources:
  pipelines:
  - pipeline: hadar
    source: kmadof.hadar
    branch: master
    trigger:
      branches:
        - master
steps:
  - script: env | sort
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: '4fa6b279-3db9-4cb0-aab8-e06c2ad550b2'
      pipeline: '72'
      branchName: 'refs/heads/master'
      buildVersionToDownload: 'specific'
      downloadType: 'single'
      downloadPath: '$(Pipeline.Workspace)/build'
      artifactName: 'drop'
      buildId: '$(resources.pipeline.hadar.runID)'

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: '4fa6b279-3db9-4cb0-aab8-e06c2ad550b2'
      definition: '72'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'specific'
      pipelineId: '$(resources.pipeline.hadar.runID)'
      artifactName: 'drop'
      targetPath: '$(Pipeline.Workspace)/pipeline'
  - download: hadar