# https://stackoverflow.com/questions/63933985/queue-azure-devops-yaml-pipeline-from-code-does-not-accept-parameters

parameters:
  - name: parameter1
    type: string

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: env | sort
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        Write-Host ${{ parameters.parameter1 }}

