parameters:
- name: PoolName
  displayName: Pool Name
  type: string
  default: Pool A
  values:
  - Pool A
  - Pool B

variables:
  ${{ if eq(parameters.PoolName, 'Pool A') }}:
      BuildArchiveLocation:  'foo'
  ${{ if eq(parameters.PoolName, 'Pool B') }}:
      BuildArchiveLocation:  'bar'

jobs:
- job: build
  displayName: Build and Test
  pool: 
    name: ${{ parameters.PoolName }}
  steps:
  - script: echo building $(Build.BuildNumber)