# https://stackoverflow.com/questions/65683895/build-a-jar-file-from-project-folder-in-a-specific-location-of-git-repository-us
name: sbt

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
- script: sbt clean
  displayName: 'Running $ sbt clean'
- script: sbt update
  displayName: 'Running $ sbt update'
- script: sbt compile
  displayName: 'Running $ sbt compile'
- script: sbt test
  displayName: 'Running $ sbt test'