# https://stackoverflow.com/questions/63933535/azure-devops-yaml-pipeline-trigger
trigger: none

pr: none

resources:        
  pipelines:
  - pipeline: build_pipeline  
    source: kmadof.devops-manual (14)
    branch: master
    trigger:
     branches:
     - '*'

steps:
- bash: env | sort
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo 'Hello world'