# https://stackoverflow.com/questions/64642449/conditions-based-on-resources-on-yaml-pipeline/64643767?noredirect=1#comment114556002_64643767

name: ref-name

trigger: none
pr: none

resources:
  repositories:
    - repository: devops
      type: github
      name: kmadof/devops-templates
      endpoint: kmadof
    - repository: azure
      type: git
      name: 'DevOps Manual/azure-functions'

variables:
  test: "true"
  azure.ref: $[ resources.repositories['azure'].ref ] 
  tools.ref: $[ resources.repositories['devops'].ref ] 
  isMain: $[eq(resources.repositories['devops'].ref, 'refs/heads/master')]

steps:
- checkout: self
- checkout: devops
- checkout: azure
- script: env | sort
  displayName: Print env variables
- bash: |
    echo "Tools version: $TOOLS_REF"
    echo "Tools version: $AZURE_REF"
    echo "Tools version: $ISMAIN"
