# https://stackoverflow.com/questions/65121138/how-to-increment-tags-in-azure-devops-pipeline-salesforce

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    #!/bin/bash          
    STR="Hello World!"
    echo $STR   
- bash: |
    #!/bin/bash          
    CurrentVersion2 = git tag -l testtag_v* --sort=creatordate | tail -n1 | awk -F'v' '{print $2}'
    echo $CurrentVersion2

    git tag -l testtag_v* --sort=creatordate | tail -n1 | awk -F'v' '{print $2}'

    CurrentVersion = `git tag -l testtag_v* --sort=creatordate | tail -n1 | awk -F'v' '{print $2}'`
    echo CURRENT VERSION: $CurrentVersion
    major=`echo $CurrentVersion | cut -d'.' -f 1`
    minor=`echo $CurrentVersion | cut -d'.' -f 2`
    minor=`expr $minor + 1`
    patch=`echo $CurrentVersion | cut -d'.' -f 3`
    NextVersion=`echo $major.$minor.$patch`
    echo NEXT VERSION: $NextVersion
    echo "##vso[task.setvariable variable=next_version;]$NextVersion"
  displayName: Get next version