trigger: none
pr: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build when changes have been pushed
  always: true
  branches:
    include:
    - branch1
    - branch2
    - master
variables:
- group: BranchVariables

steps:
- script: echo "hello $(test)"