trigger: none
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]
  isInfra: $[startsWith(variables['System.PullRequest.SourceBranch'], 'refs/heads/infra')]
  isInfra2: $[contains(variables['System.PullRequest.SourceBranch'], 'infra')]
  isPullRequestFromInfra: $[and(eq(variables['Build.Reason'], 'PullRequest'), startsWith(variables['System.PullRequest.SourceBranch'], 'refs/heads/infra'))]

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - script: echo $(isPullRequest)
    - script: echo $(isInfra)
    - script: echo $(isInfra2)
    - script: echo $(Build.Reason)
    - script: echo $(System.PullRequest.SourceBranch)
    
- stage: B
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), startsWith(variables['System.PullRequest.SourceBranch'], 'refs/heads/infra'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
     - script: echo 'FROM and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), startsWith(variables['System.PullRequest.SourceBranch'], 'refs/heads/infra'))'

- stage: C
  condition: and(succeeded(), eq(variables.isPullRequest, true), eq(variables.isInfra, true))
  dependsOn: A
  jobs:
  - job: C1
    steps:
    - script: echo 'FROM and(succeeded(), eq(variables.isPullRequest, true), eq(variables.isInfra, true))'

- stage: D
  condition: and(succeeded(), eq(variables.isPullRequestFromInfra, true))
  dependsOn: A
  jobs:
  - job: D1
    steps:
    - script: echo 'FROM eq(variables.isPullRequestFromInfra, true)'