#https://stackoverflow.com/questions/67822955/expected-a-mapping-syntax-error-when-using-parameters-section-in-azure-devop

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: 'NuGetFeedId'
    value: '11111b1d-1111-1ecb-1dc1-11f111111f11'
 
steps:
  - template: pr-validation-steps.yml
    parameters: 
      UnitTestsProjectPaths:
        - '1.Tests/1.Tests.csproj'
        - '2/2.Tests/2.Tests.csproj'
        - '3/3.Tests/3.Tests.csproj'
