# https://stackoverflow.com/questions/63896371/naming-a-nuget-package-through-yaml/63897774#63897774

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - stackoverflow/52-nuget-packager/*

pool:
  vmImage: 'ubuntu-latest'

# these variables are available throughout the build file
# just the build configuration is defined, in this case we are building Release packages
variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: --configuration $(buildConfiguration) -p:PackageID=my_id -p:PackageVersion=2.1.0
    packagesToPack: '$(System.DefaultWorkingDirectory)/stackoverflow/52-nuget-packager/SampleApp.csproj'
    versioningScheme: 'off'
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: custom
    custom: pack
    arguments: >
      $(System.DefaultWorkingDirectory)/stackoverflow/52-nuget-packager/SampleApp.csproj
      --no-build
      -p:PackageId=myId
      --output $(Build.ArtifactStagingDirectory)
      -p:PackageVersion=2.1.0
      -p:Configuration=$(buildConfiguration)
    packagesToPack: '$(System.DefaultWorkingDirectory)/stackoverflow/08-nuget-packager/SampleApp.csproj'
    versioningScheme: 'off'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    
    
- bash: ls $(Build.ArtifactStagingDirectory)
