# https://stackoverflow.com/questions/64895188/azure-pipeline-expression-does-not-work-in-template/64896723?noredirect=1#comment114758377_64896723

name: SO-Manual-86

trigger: none
pr: none

variables:
- name: assemblyVersion
#  value: ''
  value: 1.2.3.4


pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: A
  jobs:
  - job: Build
    variables: 
    - name: test
      value: $[not(variables['assemblyVersion'])]
    steps:
    - ${{if not(variables['assemblyVersion'])}}:
      - task: PowerShell@2
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            Write-Host $(assemblyVersion)
            throw "assemblyVersion was not set"
    - task: PowerShell@2
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          Write-Host $(assemblyVersion)
          Write-Host $(test)
  - template: template.yaml