# https://stackoverflow.com/questions/63678236/link-azure-devops-ci-and-cd-yaml-pipelines

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: test
    source: kmadof.dm-so-46
    trigger:
      branches:
      - master

variables:
  devopsAccount : 'thecodemanual'
  projectName : 'DevOps Manual'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo '$(Build.TriggeredBy.BuildNumber)'!
  displayName: 'Run a one-line script'

- script: |
    echo '$(Build.TriggeredBy.BuildNumber)'!
    echo '$(Build.TriggeredBy.BuildId)'!
    echo '$(Build.TriggeredBy.DefinitionId)'!
    echo '$(Build.TriggeredBy.DefinitionName)'!
    echo '$(Build.TriggeredBy.ProjectID)'!
    echo '$(Build.BuildNumber)'!
    echo '$(Build.RequestedFor)'!
    echo '$(Build.RequestedForEmail)'!
    echo '$(Build.RequestedForId)'!
  displayName: 'Run a multi-line script'
- pwsh: |
    # Get a build info
    $uri = "https://dev.azure.com/$(devopsAccount)/$(projectName)/_apis/build/builds/$(Build.BuildId)?api-version=6.0-preview.6&expand=all"

    Write-Host $uri

    # Invoke the REST call
    $result = Invoke-RestMethod -Uri $uri -Method Get -Headers @{Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"}

    $buildNumber = $result.triggerInfo.version
    Write-Host $buildNumber

    echo "##vso[task.setvariable variable=triggeredByBuildNumber]$buildNumber" #The variable doThing is set to true
- script: |
    echo '$(triggeredByBuildNumber)'!