trigger: none

# stackoverflow.com/questions/61651777/how-can-we-pass-variable-as-a-parametersas-a-list
# no PR triggers
pr: none

variables:
- name: templateParam
  value: "dir1/dir2,dir3/dir4"

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        $array = $variable.Split(',)
        Write-Host "##vso[task.setvariable variable=templateParamArray]$array"
- template: template.yaml
  parameters:
    instances: 
    ${{ each s in templateParamArray }}:
      - ${{ s }}:
    server: someServer