trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

# these variables are available throughout the build file
# just the build configuration is defined, in this case we are building Release packages
variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: --configuration $(buildConfiguration) -p:PackageID=my_id -p:PackageVersion=2.1.0
    packagesToPack: '$(System.DefaultWorkingDirectory)/stackoverflow/08-nuget-packager/SampleApp.csproj'
    versioningScheme: off
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Preparing build artifacts'
  inputs:
      command: pack
      publishWebProjects: false
      arguments: ' --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      packagesToPack: '$(System.DefaultWorkingDirectory)/stackoverflow/08-nuget-packager/SampleApp.csproj'
      versioningScheme: off
      majorVersion: '1'
      minorVersion: '2'
      patchVersion: '3'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: custom
    custom: pack
    arguments: >
      $(System.DefaultWorkingDirectory)/stackoverflow/08-nuget-packager/SampleApp.csproj
      --no-build
      -p:PackageId=my_id
      --output $(Build.ArtifactStagingDirectory)
      -p:PackageVersion=2.1.0
      -p:Configuration=$(buildConfiguration)
    packagesToPack: '$(System.DefaultWorkingDirectory)/stackoverflow/08-nuget-packager/SampleApp.csproj'
    versioningScheme: 'off'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    
- bash: ls $(Build.ArtifactStagingDirectory)
