# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - gated-checkin-angular-app/*
    exclude:
    - gated-checkin-angular-app/azure-pipelines-gc.yml

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- template: build-and-test.yaml

- bash: ls '$(Build.SourcesDirectory)/gated-checkin-angular-app/src'

- task: CopyFiles@2
  inputs:
    contents: '$(Build.SourcesDirectory)/gated-checkin-angular-app/src/ecosystem.config.js'
    targetFolder: '$(Build.SourcesDirectory)/gated-checkin-angular-app/dist/help/'
    flattenFolders: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/gated-checkin-angular-app/dist/help/'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'angularApp'
