# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Test
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    varOS: $(Agent.OS)
  steps:
    - pwsh: |
        $testVar = ''
        $os = '$(Agent.OS)'
        if ($os -eq 'Windows_NT') {
          $testVar = "I am Windows";
        } elseif ($os -eq 'Linux') {
          $testVar = "I am Linux";
        }
        Write-Host $testVar
        Write-Host "##vso[task.setvariable variable=HelloOS;isOutput=true]$testVar"
      name: Initialize
    - pwsh: |
        echo $env:TestVar
        echo $env:OS
        echo $env:AGENT_OS
        echo $env:IsMaster
        printenv
      env:
        OS: $(varOS)
        TestVar: $(Initialize.HelloOS)
        ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master')}}:
          IsMaster: "true"

