trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs:
  - job: A
    steps:
    - bash: echo "A"

- stage: DeployUS1
  dependsOn: Test    # this stage runs after Test
  jobs:
  - job: A
    steps:
    - bash: echo "A"
    - powershell: Invoke-WebRequest -URI https://some-endpoint.free.beeceptor.com/my/api/some

- stage: DeployUS2
  dependsOn: Test    # this stage runs in parallel with DeployUS1, after Test
  jobs:
  - job: A
    steps:
    - bash: echo "A"

- stage: DeployEurope
  dependsOn:         # this stage runs after DeployUS1 and DeployUS2
  - DeployUS1
  - DeployUS2
  jobs:
  - job: A
    steps:
    - bash: echo "A"