#https://stackoverflow.com/questions/65249158/azure-devops-template-pipelines-how-to-disable-ci-trigger-on-a-template/65249422?noredirect=1#comment115356077_65249422

trigger: 
- '*'
pr: none

stages:
- stage: QA
  jobs:
  - template: sub-template.yml
    parameters:
      variableGroupName: 'QA'

- stage: PROD
  jobs:
  - template: sub-template.yml
    parameters:
      variableGroupName: 'PROD'