# https://stackoverflow.com/questions/65222929/how-to-dynamically-reference-previous-jobs-in-azure-pipelines-if-there-are-any-i

trigger: none
pr: none

stages:
  - stage: BothTemplates
    displayName: 'Run both templates'
    jobs:
    - template: TemplateTest.yaml
    - template: TemplateDeploy.yaml #depends on the job in TemplateTest.yml

  - stage: OnlyTest
    dependsOn: BothTemplates
    displayName: 'Run only test template'
    jobs:
    - template: TemplateTest.yaml

  - stage: OnlyDeploy
    dependsOn: OnlyTest
    displayName: 'Run only deploy template'
    jobs:
    - template: TemplateDeploy.yaml
      parameters:
        makeExplicitDependency: false
