name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- pwsh: |
    echo some-text  > filename.txt
    cat filename.txt
    Write-Host "##vso[task.addattachment type=myattachmenttype;name=myattachmentname1;]$(System.DefaultWorkingDirectory)/filename.txt"
    Write-Host "##vso[task.uploadsummary]$(System.DefaultWorkingDirectory)/filename.txt"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        $content = @"
        Summary
        ======
        - Created resources: 0
        - Deleted resources: 0
        - Updated resources: 0
        - Unchanged resources: 117
        - Skipped resources: 1

        Details
        ----
        1. First item.
          - Item 1
          - Item 2
          - Item 3
        1. Second item.
          - Nested item 1
          - Nested item 2
          - Nested item 3

        Details
        ======

        * Skipped detail
            * MSGraph/DeviceAppManagement/MobileApps:
                * AnyDesk

        1. Skipped detail
            2. MSGraph/DeviceAppManagement/MobileApps:
                3. AnyDesk

        # Unordered list
        - Test
            - Test 2
                - Test3
        "@

        New-Item -Path . -Name "testsummary.md" -ItemType "file" -Value $content

        Get-Location

        Get-ChildItem

        Write-Host "##vso[task.uploadsummary]$(Build.SourcesDirectory)/testsummary.md"


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        $content = @"
        Summary
        ======
        - Created resources: 0
        - Deleted resources: 0
        - Updated resources: 0
        - Unchanged resources: 117
        - Skipped resources: 1

        Details
        ----
        1. First item.
          - Item 1
          - Item 2
          - Item 3
        1. Second item.
          - Nested item 1
          - Nested item 2
          - Nested item 3

        Details
        ======

        * Skipped detail
            * MSGraph/DeviceAppManagement/MobileApps:
                * AnyDesk

        1. Skipped detail
            2. MSGraph/DeviceAppManagement/MobileApps:
                3. AnyDesk

        # Unordered list
        - Test
            - Test 2
                - Test3
        "@

        New-Item -Path . -Name "testsummary2.md" -ItemType "file" -Value $content

        Get-Location

        Get-ChildItem

        Write-Host "##vso[task.uploadsummary]$(Build.SourcesDirectory)/testsummary2.md"
        Write-Host "##vso[task.addattachment type=myattachmenttype;name=SomeName;]$(Build.SourcesDirectory)/testsummary2.md"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        
        Write-Host "##vso[task.addattachment type=terraform-plan;name=SomeName;]$(Build.SourcesDirectory)/testsummary.md"