#https://stackoverflow.com/questions/64648214/validate-yaml-file-using-powershell-cmd-in-azure-pipeline

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: A
  jobs:
  - job: JA
    steps:
    - pwsh: Install-Module powershell-yaml -Force
    - pwsh: |
        $content = Get-Content -Path stackoverflow\80-yaml\test.yaml -Raw
        $correct = true
        try {
          $obj = ConvertFrom-Yaml $content
          Write-Host $obj
        }
        catch {
            Write-Host "An error occurred:"
            
            $correct = false
        }
        

        
        Write-Host $correct
        
      