#https://stackoverflow.com/questions/63775982/how-to-get-failed-step-number-in-azure-pipeline

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    exit 1
  displayName: 'Run a multi-line script'
