trigger:
  branches:
    include:
      - refs/tags/ops-v*
    exclude:
      - refs/tags/qa*
      - refs/tags/dev*

pr: none

stages:
- stage: Init
  jobs:
  - job: CheckoutInit
    steps:
    - checkout: self
    - script: echo '*do something 2*'
