trigger:
- master

variables:
  BuildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

#https://stackoverflow.com/questions/61910176/how-to-deploy-a-webapp-from-a-folder-not-a-zip-in-azure-devops

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: true
    projects: |
      $(Build.SourcesDirectory)/stackoverflow/32-deploy-folder/SampleApp/SampleApp.csproj

- pwsh: ls $(Build.ArtifactStagingDirectory)/SampleApp

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'PublishProfile'
    PublishProfilePath: '$(System.DefaultWorkingDirectory)/stackoverflow/32-deploy-folder/SampleApp/Properties/PublishProfiles/SampleApp20200520132633 - Web Deploy.pubxml'
    PublishProfilePassword:  $(password)
    Package: '$(Build.ArtifactStagingDirectory)/SampleApp/*'