
trigger:
  branches:
    include:
    - '*'
    exclude:
    - master
  paths:
    include:
    - build-docker-image/SampleAppForDocker/*
    exclude:
    - build-docker-image/SampleAppForDocker/*.ymal

# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: rg-the-code-manual
    scriptType: pscore
    workingDirectory: $(Build.SourcesDirectory)/build-docker-image/SampleAppForDocker/
    scriptLocation: inlineScript
    inlineScript: |
      az acr build --image sampleappfordocker:build-on-acr --registry devopsmanual --file DOCKERFILE .