
trigger:
  branches:
    include:
    - '*'
    exclude:
    - master
  paths:
    include:
    - build-docker-image/SampleAppForDocker/*
    exclude:
    - build-docker-image/SampleAppForDocker/*.ymal

# no PR triggers
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'SomeImage'

jobs:
- job: BuildImage
  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: devopsmanual-acr

  - task: Docker@2
    displayName: Build and Push
    inputs:
      repository: $(imageName)
      command: buildAndPush
      buildContext: $(Build.SourcesDirectory)/build-docker-image/SampleAppForDocker
      Dockerfile: build-docker-image/SampleAppForDocker/DOCKERFILE
      tags: |
        build-on-agent
        $(Build.BuildNumber)

  - task: Docker@2
    displayName: Logout of ACR
    inputs:
      command: logout
      containerRegistry: devopsmanual-acr

- deployment: DeployWebApp
  displayName: 'Deployment to Azure Web App'
  dependsOn: BuildImage
  pool:
    vmImage: 'Ubuntu-20.04'
  environment: development
  strategy:
    runOnce:
      deploy:
        steps:
        - pwsh: Write-Host "Hello"
        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy Azure App Service'
          inputs:
            azureSubscription: rg-the-code-manual
            appType: webAppContainer
            WebAppName: test-container-application
            DockerNamespace: devopsmanual.azurecr.io
            DockerRepository: sampleappfordocker
            DockerImageTag: '$(Build.BuildNumber)'